/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FileId = IDL.Text;
export const NoteInput = IDL.Record({
  'topic' : IDL.Text,
  'semester' : IDL.Nat,
  'subject' : IDL.Text,
  'unit' : IDL.Text,
  'year' : IDL.Nat,
  'aiSummary' : IDL.Text,
  'department' : IDL.Text,
  'transcript' : IDL.Text,
  'pdfFileId' : FileId,
});
export const Timestamp = IDL.Int;
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'semester' : IDL.Nat,
  'subject' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Principal,
  'unit' : IDL.Text,
  'year' : IDL.Nat,
  'aiSummary' : IDL.Text,
  'department' : IDL.Text,
  'transcript' : IDL.Text,
  'pdfFileId' : FileId,
});
export const AnalyticsData = IDL.Record({
  'notesPerDay' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'activeStudents' : IDL.Nat,
  'papersPerDepartment' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'totalDownloads' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'totalStudents' : IDL.Nat,
  'totalSubjects' : IDL.Nat,
  'totalNotes' : IDL.Nat,
  'totalQuestionPapers' : IDL.Nat,
  'recentNotes' : IDL.Vec(Note),
});
export const NoteFilters = IDL.Record({
  'semester' : IDL.Opt(IDL.Nat),
  'subject' : IDL.Opt(IDL.Text),
  'unit' : IDL.Opt(IDL.Text),
  'year' : IDL.Opt(IDL.Nat),
  'department' : IDL.Opt(IDL.Text),
});
export const QuestionPaper = IDL.Record({
  'id' : IDL.Nat,
  'semester' : IDL.Nat,
  'subject' : IDL.Text,
  'regulation' : IDL.Text,
  'createdAt' : Timestamp,
  'year' : IDL.Nat,
  'paperType' : IDL.Text,
  'department' : IDL.Text,
  'pdfFileId' : FileId,
  'uploadedBy' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : IDL.Text,
});
export const QuestionPaperInput = IDL.Record({
  'semester' : IDL.Nat,
  'subject' : IDL.Text,
  'regulation' : IDL.Text,
  'year' : IDL.Nat,
  'paperType' : IDL.Text,
  'department' : IDL.Text,
  'pdfFileId' : FileId,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNote' : IDL.Func([NoteInput], [IDL.Opt(Note)], []),
  'deleteNote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'generateAISummary' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'getAnalytics' : IDL.Func([IDL.Nat], [AnalyticsData], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
  'getNotes' : IDL.Func(
      [NoteFilters, IDL.Nat, IDL.Nat],
      [IDL.Record({ 'total' : IDL.Nat, 'notes' : IDL.Vec(Note) })],
      ['query'],
    ),
  'getQuestionPapers' : IDL.Func(
      [NoteFilters, IDL.Nat, IDL.Nat],
      [IDL.Record({ 'total' : IDL.Nat, 'papers' : IDL.Vec(QuestionPaper) })],
      ['query'],
    ),
  'getStudents' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'searchNotes' : IDL.Func([IDL.Text, NoteFilters], [IDL.Vec(Note)], ['query']),
  'searchQuestionPapers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(QuestionPaper)],
      ['query'],
    ),
  'setOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
  'setUserProfile' : IDL.Func([IDL.Text], [UserProfile], []),
  'summarizeTranscript' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'updateNote' : IDL.Func([IDL.Nat, NoteInput], [IDL.Opt(Note)], []),
  'uploadQuestionPaper' : IDL.Func(
      [QuestionPaperInput],
      [IDL.Opt(QuestionPaper)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FileId = IDL.Text;
  const NoteInput = IDL.Record({
    'topic' : IDL.Text,
    'semester' : IDL.Nat,
    'subject' : IDL.Text,
    'unit' : IDL.Text,
    'year' : IDL.Nat,
    'aiSummary' : IDL.Text,
    'department' : IDL.Text,
    'transcript' : IDL.Text,
    'pdfFileId' : FileId,
  });
  const Timestamp = IDL.Int;
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'semester' : IDL.Nat,
    'subject' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Principal,
    'unit' : IDL.Text,
    'year' : IDL.Nat,
    'aiSummary' : IDL.Text,
    'department' : IDL.Text,
    'transcript' : IDL.Text,
    'pdfFileId' : FileId,
  });
  const AnalyticsData = IDL.Record({
    'notesPerDay' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'activeStudents' : IDL.Nat,
    'papersPerDepartment' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'totalDownloads' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'totalStudents' : IDL.Nat,
    'totalSubjects' : IDL.Nat,
    'totalNotes' : IDL.Nat,
    'totalQuestionPapers' : IDL.Nat,
    'recentNotes' : IDL.Vec(Note),
  });
  const NoteFilters = IDL.Record({
    'semester' : IDL.Opt(IDL.Nat),
    'subject' : IDL.Opt(IDL.Text),
    'unit' : IDL.Opt(IDL.Text),
    'year' : IDL.Opt(IDL.Nat),
    'department' : IDL.Opt(IDL.Text),
  });
  const QuestionPaper = IDL.Record({
    'id' : IDL.Nat,
    'semester' : IDL.Nat,
    'subject' : IDL.Text,
    'regulation' : IDL.Text,
    'createdAt' : Timestamp,
    'year' : IDL.Nat,
    'paperType' : IDL.Text,
    'department' : IDL.Text,
    'pdfFileId' : FileId,
    'uploadedBy' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : IDL.Text,
  });
  const QuestionPaperInput = IDL.Record({
    'semester' : IDL.Nat,
    'subject' : IDL.Text,
    'regulation' : IDL.Text,
    'year' : IDL.Nat,
    'paperType' : IDL.Text,
    'department' : IDL.Text,
    'pdfFileId' : FileId,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNote' : IDL.Func([NoteInput], [IDL.Opt(Note)], []),
    'deleteNote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'generateAISummary' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'getAnalytics' : IDL.Func([IDL.Nat], [AnalyticsData], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
    'getNotes' : IDL.Func(
        [NoteFilters, IDL.Nat, IDL.Nat],
        [IDL.Record({ 'total' : IDL.Nat, 'notes' : IDL.Vec(Note) })],
        ['query'],
      ),
    'getQuestionPapers' : IDL.Func(
        [NoteFilters, IDL.Nat, IDL.Nat],
        [IDL.Record({ 'total' : IDL.Nat, 'papers' : IDL.Vec(QuestionPaper) })],
        ['query'],
      ),
    'getStudents' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'searchNotes' : IDL.Func(
        [IDL.Text, NoteFilters],
        [IDL.Vec(Note)],
        ['query'],
      ),
    'searchQuestionPapers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(QuestionPaper)],
        ['query'],
      ),
    'setOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
    'setUserProfile' : IDL.Func([IDL.Text], [UserProfile], []),
    'summarizeTranscript' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'updateNote' : IDL.Func([IDL.Nat, NoteInput], [IDL.Opt(Note)], []),
    'uploadQuestionPaper' : IDL.Func(
        [QuestionPaperInput],
        [IDL.Opt(QuestionPaper)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };