/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsData {
  'notesPerDay' : Array<[string, bigint]>,
  'activeStudents' : bigint,
  'papersPerDepartment' : Array<[string, bigint]>,
  'totalDownloads' : bigint,
}
export interface DashboardStats {
  'totalStudents' : bigint,
  'totalSubjects' : bigint,
  'totalNotes' : bigint,
  'totalQuestionPapers' : bigint,
  'recentNotes' : Array<Note>,
}
export type FileId = string;
export interface Note {
  'id' : bigint,
  'topic' : string,
  'semester' : bigint,
  'subject' : string,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'unit' : string,
  'year' : bigint,
  'aiSummary' : string,
  'department' : string,
  'transcript' : string,
  'pdfFileId' : FileId,
}
export interface NoteFilters {
  'semester' : [] | [bigint],
  'subject' : [] | [string],
  'unit' : [] | [string],
  'year' : [] | [bigint],
  'department' : [] | [string],
}
export interface NoteInput {
  'topic' : string,
  'semester' : bigint,
  'subject' : string,
  'unit' : string,
  'year' : bigint,
  'aiSummary' : string,
  'department' : string,
  'transcript' : string,
  'pdfFileId' : FileId,
}
export interface QuestionPaper {
  'id' : bigint,
  'semester' : bigint,
  'subject' : string,
  'regulation' : string,
  'createdAt' : Timestamp,
  'year' : bigint,
  'paperType' : string,
  'department' : string,
  'pdfFileId' : FileId,
  'uploadedBy' : Principal,
}
export interface QuestionPaperInput {
  'semester' : bigint,
  'subject' : string,
  'regulation' : string,
  'year' : bigint,
  'paperType' : string,
  'department' : string,
  'pdfFileId' : FileId,
}
export type Timestamp = bigint;
export interface UserProfile {
  'principal' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNote' : ActorMethod<[NoteInput], [] | [Note]>,
  'deleteNote' : ActorMethod<[bigint], boolean>,
  'generateAISummary' : ActorMethod<[string], [] | [string]>,
  'getAnalytics' : ActorMethod<[bigint], AnalyticsData>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getNote' : ActorMethod<[bigint], [] | [Note]>,
  'getNotes' : ActorMethod<
    [NoteFilters, bigint, bigint],
    { 'total' : bigint, 'notes' : Array<Note> }
  >,
  'getQuestionPapers' : ActorMethod<
    [NoteFilters, bigint, bigint],
    { 'total' : bigint, 'papers' : Array<QuestionPaper> }
  >,
  'getStudents' : ActorMethod<[], Array<UserProfile>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOpenAIConfigured' : ActorMethod<[], boolean>,
  'searchNotes' : ActorMethod<[string, NoteFilters], Array<Note>>,
  'searchQuestionPapers' : ActorMethod<[string], Array<QuestionPaper>>,
  'setOpenAIApiKey' : ActorMethod<[string], undefined>,
  'setUserProfile' : ActorMethod<[string], UserProfile>,
  'summarizeTranscript' : ActorMethod<[string], [] | [string]>,
  'updateNote' : ActorMethod<[bigint, NoteInput], [] | [Note]>,
  'uploadQuestionPaper' : ActorMethod<
    [QuestionPaperInput],
    [] | [QuestionPaper]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];